defaults: &defaults
  working_directory: /workspace
  docker:
    - image: node:14.5

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: build
          command: cp build/index.html build/200.html
      - run:
          name: copy ci config
          command: cp -r .circleci/ ./public/.circleci/
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - package-lock.json
      - persist_to_workspace:
          root: /workspace
          paths:
            - build
            - package.json
            - .git
  deploy:
      <<: *defaults
      steps:
        - run:
            name: install deps
            command: apt-get update -y; apt-get install git -y
        - attach_workspace:
            at: /workspace
        - run:
            name: git config
            command: git config --global user.email "deploy@circleci.com" && git config --global user.name "Circle CI"
        - run:
            name: ssh alias override key verification
            command: alias ssh='ssh -o StrictHostKeyChecking=no'  && mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
        - run:
            name: install gh-pages
            command: npm i gh-pages
        - run:
            name: gh-pages deploy
            command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master